## Home Work 1

### Задача 1


$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [17]:
def share_bread(N, K):
    # your code here
    y = K % N # остаток от деления = сколько кусков остаток в корзине
    x = K // N # целочисленное деление = сколько кусков хлеба каждому 
    print (x, y)
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)


4 2


### Задача 2

In [63]:
def leap_year(year):
    # your code here
    if year % 4 != 0:
        text_result = "YOU SHALL NOT PASS"
    elif year % 100 == 0 and  year % 400 != 0:
        text_result = "YOU SHALL NOT PASS"
    else:
        text_result = "YOU SHALL PASS"
    return text_result

leap_year(400)

'YOU SHALL PASS'


### Задача 3

In [ ]:
def amulet_area(a, b, c):
    # your code here
    p = (a + b + c) / 2
    S = (p * (p - a) * (p - b) * (p - c)) ** 0.5
    return S

assert amulet_area(3, 4, 5) == 6

### Задача 4

### ??
1) мне нужна подсказка как записать формулы в Python

2) я не могу прочитать формулу Косинусное расстояние




### Задача 5

#### Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

### исправленный код

In [3]:

import numpy as np
my_array = np.random.rand(101)
print(np.max(my_array), np.min(my_array))

# ищем индекс макс и мин значения в массиве
maximum_value_index = np.argmax(my_array)
minimum_value_index = np.argmin(my_array)
print(f' - maximum_value_index = {maximum_value_index},  \n - minimum_value_index = {minimum_value_index}')

print('\n - Меняем макс и мин значения в массиве. Остальные значения без изменений')
my_array[maximum_value_index] = 1.0
my_array[minimum_value_index] = 0.0
print(my_array)


0.9828839114630501 0.010257395709995731
 - maximum_value_index = 18,  
 - minimum_value_index = 44

 - Меняем макс и мин значения в массиве. Остальные значения без изменений
[0.70482521 0.3616785  0.1513441  0.51676301 0.79514152 0.39189073
 0.72955576 0.27935836 0.55668158 0.50416888 0.90397075 0.41024362
 0.43523239 0.24757587 0.55868177 0.30449118 0.52525196 0.94680013
 1.         0.96941041 0.33382495 0.23589118 0.06531394 0.45494193
 0.06492074 0.54809148 0.16297348 0.50551119 0.57483142 0.64802945
 0.96106804 0.18499083 0.89482417 0.09290715 0.44141461 0.37816606
 0.06822678 0.08644877 0.46062548 0.18890909 0.08611028 0.06716098
 0.16080551 0.69675664 0.         0.34126861 0.80922771 0.28011049
 0.62178567 0.66096236 0.46000472 0.85172634 0.09746071 0.42537672
 0.62432048 0.61403459 0.88887144 0.41989808 0.472913   0.11370272
 0.18803661 0.46679125 0.699604   0.61712598 0.75791201 0.25819028
 0.53973673 0.82331474 0.10170872 0.84802504 0.6679676  0.63204649
 0.32259842 0.64294057

### старая редакция

In [1]:

import numpy as np
my_array = np.random.rand(101)
print(np.max(my_array), np.min(my_array))
print()

# ищем индекс макс и мин значения в массиве
max_value = 0
min_value = 1
# ищем максимальное и минимально значение массива
for index, value in enumerate(my_array):
    if value > max_value:
        max_value = value
        max_index = index # индекс максимального значения
    if value < min_value:
        min_value = value
        min_index = index  # индекс минимального значения

print(f' - макс. значение [{max_index}] {max_value}, \n - мин. значение [{min_index}] {min_value}')

print('\nМеняем макс и мин значения в массиве. Остальные значения без изменений')
my_array[max_index] = 1.0
my_array[min_index] = 0.0
my_array
print(my_array)



0.9918992056135217 0.004938363316116301

 - макс. значение [84] 0.9918992056135217, 
 - мин. значение [25] 0.004938363316116301

Меняем макс и мин значения в массиве. Остальные значения без изменений
[0.15786426 0.74427838 0.11275061 0.63483528 0.86733104 0.48308573
 0.33009571 0.82635954 0.8262514  0.90942794 0.5371119  0.45811641
 0.40495698 0.68832591 0.61956067 0.97892803 0.86620723 0.14207716
 0.62674224 0.71380821 0.48567532 0.3853033  0.58660079 0.80357891
 0.64705921 0.         0.33880153 0.85858783 0.29831051 0.56333005
 0.71287854 0.9574195  0.90034685 0.33659418 0.5149434  0.07448734
 0.35861593 0.73417011 0.64259172 0.74837666 0.01025292 0.71504287
 0.34677045 0.75973339 0.558873   0.13482564 0.43389925 0.34823166
 0.51438212 0.87318507 0.46981039 0.36653415 0.76154238 0.27861095
 0.24881602 0.07058076 0.47655035 0.28165199 0.12214192 0.31622888
 0.55750496 0.36956754 0.77331157 0.20977434 0.41391733 0.37500382
 0.70369882 0.01533075 0.38872073 0.65567329 0.8590485  0.47602

#### Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 



### исправленный код

In [5]:
import numpy as np

arr = np.random.randint(0, 50,  size=(5,6))
print('Сгенерированная матрица\n', arr)

print(' - ищем наибольшее значение в каждом столбце')
max_val_col = np.max(arr, axis = 0)
print( f'max_val_col {max_val_col} \n' )

print(' - ищем ИНДЕКС СТОЛБЦА где находится наибольшее значение')
index_max_col = np.argmax(max_val_col)
print( f'index_max_col {index_max_col}\n' )

print(' - столбец с наибольшим значением')
print(arr[ :, index_max_col])


Сгенерированная матрица
 [[15  2 13 36 46 47]
 [40 36 32 35 19 29]
 [12  2  6  3 46 10]
 [16 35 12 36 47 20]
 [28 23 38 29 13  3]]
 - ищем наибольшее значение в каждом столбце
max_val_col [40 36 38 36 47 47] 

 - ищем ИНДЕКС СТОЛБЦА где находится наибольшее значение
index_max_col 4

 - столбец с наибольшим значением
[46 19 46 47 13]


### старая редакция

In [2]:

'''
Создайте array размером 5 на 6 с целыми числами в интервале [0,50].
Напечатайте колонку, которая содержит максимальный элемент полученной матрицы
'''

import numpy as np

arr = np.random.randint(0, 50,  size=(5,6))
print('Сгенерированная матрица\n', arr)

# ищем наибольший элемент в матрице и его индекс
max_value = 0
for index_row, value in enumerate(arr):
    for index_col, value_row in enumerate(arr):
        value = arr[index_row][index_col]
        if value > max_value:
            max_value = value
            # индексы максимального значения
            max_index_row = index_row   # это значение нам особо не нужно, но ладно пусть будет
            max_index_col = index_col

print(f'\nмаксимальное значением в матрице [{ max_index_row }][{max_index_col }] = { arr[max_index_row][max_index_col] }')
print('столбец с максимальным значением в матрице:')
i = 0
for k in arr:
    col_print = arr[i][max_index_col]
    i += 1
    print(col_print)



Сгенерированная матрица
 [[24 25 46 42 41 14]
 [21 22 30 30  4 48]
 [43  5 11 26 23 18]
 [ 0  4  3 41 43 19]
 [18 13 43 18 21 27]]

максимальное значением в матрице [0][2] = 46
столбец с максимальным значением в матрице:
46
30
11
3
43


#### Напишите функцию, которая принимает на вохд матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [1]:
import numpy as np

Y =  np.random.randint(4, 6, size=(10,3))
print('Сгенерированная матрица\n', Y)

print('\nУникальная матрица')
uniq_matrix = np.unique(Y, axis = 0)
print( uniq_matrix)


Сгенерированная матрица
 [[5 5 5]
 [5 5 4]
 [4 5 4]
 [5 5 4]
 [4 4 5]
 [4 4 4]
 [4 5 4]
 [4 5 5]
 [4 5 5]
 [4 5 4]]

Уникальная матрица
[[4 4 4]
 [4 4 5]
 [4 5 4]
 [4 5 5]
 [5 5 4]
 [5 5 5]]
