## Home Work 1

### Задача 1


$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [17]:
def share_bread(N, K):
    # your code here
    y = K % N # остаток от деления = сколько кусков остаток в корзине
    x = K // N # целочисленное деление = сколько кусков хлеба каждому 
    print (x, y)
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)


4 2


### Задача 2

In [63]:
def leap_year(year):
    # your code here
    if year % 4 != 0:
        text_result = "YOU SHALL NOT PASS"
    elif year % 100 == 0 and  year % 400 != 0:
        text_result = "YOU SHALL NOT PASS"
    else:
        text_result = "YOU SHALL PASS"
    return text_result

leap_year(400)

'YOU SHALL PASS'


### Задача 3

In [ ]:
def amulet_area(a, b, c):
    # your code here
    p = (a + b + c) / 2
    S = (p * (p - a) * (p - b) * (p - c)) ** 0.5
    return S

assert amulet_area(3, 4, 5) == 6

### Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.

#### Евклидово расстояние

In [1]:
import numpy as np

a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)


def cal_euclidean(a, b):    
    
    # квадраты векторов
    square = np.square(a - b)
    # сумма квадратов векторов
    sum_square = np.sum(square)

    # квадратный корень
    distance = np.sqrt(sum_square)
    
    return distance


cal_euclidean(a, b)

26.68332812825267

#### Расстояние Манхэттена

In [ ]:
import numpy as np

a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)

def cal_manhattan(a, b):    
    distance = np.sum(np.abs(a - b))
    return distance

cal_manhattan(a, b)


#### Косинусное расстояние

In [2]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)

def cal_cosine(a, b):    
    distance = 1 - np.dot(a, b)/(np.linalg.norm(a)*(np.linalg.norm(b)))
    return distance

cal_cosine(a, b)


1.0371171113416584

### Задача 5

In [1]:

import numpy as np
my_array = np.random.rand(101)
print(np.max(my_array), np.min(my_array))
print()

# ищем индекс макс и мин значения в массиве
max_value = 0
min_value = 1
# ищем максимальное и минимально значение массива
for index, value in enumerate(my_array):
    if value > max_value:
        max_value = value
        max_index = index # индекс максимального значения
    if value < min_value:
        min_value = value
        min_index = index  # индекс минимального значения

print(f' - макс. значение [{max_index}] {max_value}, \n - мин. значение [{min_index}] {min_value}')

print('\nМеняем макс и мин значения в массиве. Остальные значения без изменений')
my_array[max_index] = 1.0
my_array[min_index] = 0.0
my_array
print(my_array)



0.9918992056135217 0.004938363316116301

 - макс. значение [84] 0.9918992056135217, 
 - мин. значение [25] 0.004938363316116301

Меняем макс и мин значения в массиве. Остальные значения без изменений
[0.15786426 0.74427838 0.11275061 0.63483528 0.86733104 0.48308573
 0.33009571 0.82635954 0.8262514  0.90942794 0.5371119  0.45811641
 0.40495698 0.68832591 0.61956067 0.97892803 0.86620723 0.14207716
 0.62674224 0.71380821 0.48567532 0.3853033  0.58660079 0.80357891
 0.64705921 0.         0.33880153 0.85858783 0.29831051 0.56333005
 0.71287854 0.9574195  0.90034685 0.33659418 0.5149434  0.07448734
 0.35861593 0.73417011 0.64259172 0.74837666 0.01025292 0.71504287
 0.34677045 0.75973339 0.558873   0.13482564 0.43389925 0.34823166
 0.51438212 0.87318507 0.46981039 0.36653415 0.76154238 0.27861095
 0.24881602 0.07058076 0.47655035 0.28165199 0.12214192 0.31622888
 0.55750496 0.36956754 0.77331157 0.20977434 0.41391733 0.37500382
 0.70369882 0.01533075 0.38872073 0.65567329 0.8590485  0.47602

In [2]:

'''
Создайте array размером 5 на 6 с целыми числами в интервале [0,50].
Напечатайте колонку, которая содержит максимальный элемент полученной матрицы
'''

import numpy as np

arr = np.random.randint(0, 50,  size=(5,6))
print('Сгенерированная матрица\n', arr)

# ищем наибольший элемент в матрице и его индекс
max_value = 0
for index_row, value in enumerate(arr):
    for index_col, value_row in enumerate(arr):
        value = arr[index_row][index_col]
        if value > max_value:
            max_value = value
            # индексы максимального значения
            max_index_row = index_row   # это значение нам особо не нужно, но ладно пусть будет
            max_index_col = index_col

print(f'\nмаксимальное значением в матрице [{ max_index_row }][{max_index_col }] = { arr[max_index_row][max_index_col] }')
print('столбец с максимальным значением в матрице:')
i = 0
for k in arr:
    col_print = arr[i][max_index_col]
    i += 1
    print(col_print)



Сгенерированная матрица
 [[24 25 46 42 41 14]
 [21 22 30 30  4 48]
 [43  5 11 26 23 18]
 [ 0  4  3 41 43 19]
 [18 13 43 18 21 27]]

максимальное значением в матрице [0][2] = 46
столбец с максимальным значением в матрице:
46
30
11
3
43


In [ ]:

'''
Напишите функцию, которая принимает на вохд матрицу (array) X
и возвращает все её уникальные строки в виде новой матрицы.
'''

import numpy as np

#def get_unique_rows(X):
    # Your code here
#    return X_unique

X = np.random.randint(4, 6, size=(10,3))
print('Сгенерированная матрица\n', X)


#a = X[0]
#b = X[1]
#f = a == b
#print(f)
#print(type(b))
#row = U[][]

print('\nсравнение строк')
i = 1
uniq_matrix = []
uniq_matrix.append(X[1])
#print('uniq_matrix \n', uniq_matrix)
#print(uniq_matrix[0])


for row_one in uniq_matrix:
    a = list(row_one)
    for row_next in X:
        b = list(row_next)
        if a != b:
            uniq_matrix.append(X[b])

print(uniq_matrix)

    #for
    #if row != row_in_X:



#get_unique_rows(X)
